app:
    image: michcald/app
    volumes:
        - volumes/app/src/:/var/www/symfony
    tty: true
db:
    image: michcald/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    image: michcald/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - app
    links:
        - db
#        - redis
#        - beanstalkd
nginx:
    image: michcald/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - volumes/nginx/var/logs/nginx/:/var/log/nginx
redis:
    image: michcald/redis
    ports:
        - 6379:6379
    volumes:
        - logs/redis/:/var/log/redis
beanstalkd:
    image: michcald/beanstalkd
    ports:
        - 11300:11300
    volumes:
        - logs/beanstalkd:/var/log/beanstalkd
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - images/elk/logstash:/etc/logstash
        - images/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - app
        - php
        - nginx
#        - beanstalkd # CHANGE CONFIG
#        - redis # CHANGE CONFIG
#        - db # CHANGE CONFIG
