mysql:
    build: images/mysql
    hostname: mysql_host
    tty: true
    restart: always
    expose:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
redis:
    build: images/redis
    hostname: redis_host
    tty: true
    restart: always
    expose:
        - "6379:6379"
    volumes:
        - "./volumes/redis/:/var/log/redis"
beanstalkd:
    build: images/beanstalkd
    hostname: beanstalkd_host
    expose:
        - "11300:11300"
    volumes:
        - "./volumes/beanstalkd:/var/log/beanstalkd"
app:
    build: images/app
    tty: true
    restart: always
    volumes:
        - "./volumes/app/src/:/var/www/myapp"
php:
    build: images/php-fpm
    hostname: php_host
    expose:
        - "9000:9000"
    volumes_from:
        - app
    links:
        - mysql
        - redis
        - beanstalkd
nginx:
    build: images/nginx
    hostname: nginx_host
    ports:
        - "8080:80"
    links:
        - php
    volumes_from:
        - app
    volumes:
        - "./volumes/nginx:/var/log/nginx"
elk:
    image: willdurand/elk
    hostname: elk_host
    ports:
        - "8081:80"
    volumes:
        - "./volumes/elk/logstash:/etc/logstash"
        - "./volumes/elk/logstash/patterns:/opt/logstash/patterns"
    volumes_from:
        - app
        - php
        - nginx
